# Generated by Django 5.2.17 on 2026-08-14 22:29

from django.db import migrations, models


def migrate_staff_role_to_support(apps, schema_editor):
    """The generic "Staff" role is replaced by the more specific
    Support/Sales/Management/Accounts roles -- every existing user who
    had the old "staff" role becomes "support" by default (an admin can
    reassign anyone to a more specific role afterwards)."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="staff").update(role="support")


def reverse_support_role_to_staff(apps, schema_editor):
    # Best-effort reverse: only rows that were exactly migrated from
    # "staff" -> "support" get reversed; any account an admin has since
    # actively re-set to "support" would also get swept up, which is an
    # accepted limitation of reversing a lossy data migration.
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="support").update(role="staff")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_twofactorauth_twofactorbackupcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("support", "Support"),
                    ("sales", "Sales"),
                    ("technician", "Technician"),
                    ("management", "Management"),
                    ("accounts", "Accounts"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_staff_role_to_support, reverse_support_role_to_staff),
    ]
