# Generated by Django 5.2.17 on 2026-08-16 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_allowed_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_partners",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="Partner ids this staff member can see customers for. Empty = unrestricted (sees all partners).",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="visible_partners",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="Subset of allowed_partners this staff member currently wants shown by default. Empty = show all allowed.",
                size=None,
            ),
        ),
    ]
