# Generated by Django 5.2.17 on 2026-08-19 22:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_allowed_partners_user_visible_partners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="allowed_sections",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("scheduling", "Scheduling"),
                        ("customers", "Customers"),
                        ("services", "Services"),
                        ("finance", "Finance"),
                        ("inventory", "Stock / Inventory"),
                        ("networking", "Networking"),
                        ("tickets", "Support Tickets"),
                        ("vehicles", "Vehicles"),
                        ("bulk_email", "Bulk Email"),
                        ("configs", "Configs"),
                        ("accountant", "Accountant"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Sections this staff member can see/use. Empty = unrestricted (sees everything). Ignored for Admin.",
                size=None,
            ),
        ),
    ]
