# Generated by Django 5.2.17 on 2026-08-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_alter_customer_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome message"),
                            ("statement", "Statement"),
                            ("invoice", "Invoice"),
                            ("payment_reminder", "Payment reminder"),
                            ("suspension", "Suspension notification"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=255)),
                (
                    "body_html",
                    models.TextField(
                        help_text="HTML email body. Supports Django template syntax, e.g. {{ customer_name }}."
                    ),
                ),
                (
                    "has_attachment",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Whether this template type sends a generated PDF attachment.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_key",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome message"),
                            ("statement", "Statement"),
                            ("invoice", "Invoice"),
                            ("payment_reminder", "Payment reminder"),
                            ("suspension", "Suspension notification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "batch_id",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="customers.customer",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
