# Generated by Django 5.2.17 on 2026-08-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_seed_quote_proforma_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="template_key",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome message"),
                    ("quote", "Quote"),
                    ("proforma", "Pro forma invoice"),
                    ("statement", "Statement"),
                    ("invoice", "Invoice"),
                    ("payment_reminder", "Payment reminder"),
                    ("suspension", "Suspension notification"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome message"),
                    ("quote", "Quote"),
                    ("proforma", "Pro forma invoice"),
                    ("statement", "Statement"),
                    ("invoice", "Invoice"),
                    ("payment_reminder", "Payment reminder"),
                    ("suspension", "Suspension notification"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
