# Generated by Django 5.2.17 on 2026-08-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_emaillog_template_key_alter_emailtemplate_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        help_text="e.g. smtp.office365.com. Leave blank to use the server's default.",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank to use the server's default.",
                        null=True,
                    ),
                ),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                ("smtp_password", models.CharField(blank=True, max_length=255)),
                (
                    "use_tls",
                    models.BooleanField(
                        blank=True,
                        help_text="Leave unset to use the server's default.",
                        null=True,
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        blank=True,
                        help_text="Leave unset to use the server's default.",
                        null=True,
                    ),
                ),
                (
                    "default_from_email",
                    models.CharField(
                        blank=True,
                        help_text='"From" header for outgoing mail, e.g. "Skybre <no-reply@skybre.co.za>".',
                        max_length=255,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Used in email subjects/bodies and generated PDFs.",
                        max_length=100,
                    ),
                ),
                (
                    "site_url",
                    models.CharField(
                        blank=True,
                        help_text="Base URL used to build links inside emails, e.g. https://skybre.co.za",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email settings",
                "verbose_name_plural": "Email settings",
            },
        ),
    ]
