from django.db import migrations

# Default content for the new "payment_received" template slot added
# alongside the recurring-billing feature -- sent from PaymentSerializer.
# create() for any payment (manual or recurring-engine), not just ones
# generated by billing.recurring. Mirrors the pattern in
# 0003_seed_quote_proforma_templates.py. No PDF attachment (has_attachment
# stays False) -- this is just a short receipt notification, unlike
# invoice/quote/proforma/statement.
DEFAULTS = [
    {
        "key": "payment_received",
        "name": "Payment received",
        "subject": "Payment received — thank you, {{ customer_name }}",
        "has_attachment": False,
        "body_html": (
            "<p>Hi {{ customer_name }},</p>"
            "<p>We've received your payment of <strong>R {{ payment_amount }}</strong>"
            "{% if invoice_number %} for invoice <strong>{{ invoice_number }}</strong>{% endif %}. Thank you!</p>"
            "<p>Your current account balance is R {{ balance }}.</p>"
            "<p>Thanks,<br>The {{ company_name }} Team</p>"
        ),
    },
]


def seed_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("notifications", "EmailTemplate")
    for d in DEFAULTS:
        EmailTemplate.objects.get_or_create(key=d["key"], defaults=d)


def remove_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("notifications", "EmailTemplate")
    EmailTemplate.objects.filter(key__in=[d["key"] for d in DEFAULTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_emaillog_template_key_alter_emailtemplate_key"),
    ]

    operations = [
        migrations.RunPython(seed_templates, remove_templates),
    ]
