# Generated by Django 5.2.17 on 2026-08-24 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_seed_payment_received_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslip_email_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="template_key",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome message"),
                    ("quote", "Quote"),
                    ("proforma", "Pro forma invoice"),
                    ("statement", "Statement"),
                    ("invoice", "Invoice"),
                    ("payment_reminder", "Payment reminder"),
                    ("suspension", "Suspension notification"),
                    ("payment_received", "Payment received"),
                    ("payslip", "Payslip"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome message"),
                    ("quote", "Quote"),
                    ("proforma", "Pro forma invoice"),
                    ("statement", "Statement"),
                    ("invoice", "Invoice"),
                    ("payment_reminder", "Payment reminder"),
                    ("suspension", "Suspension notification"),
                    ("payment_received", "Payment received"),
                    ("payslip", "Payslip"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
