# Generated by Django 5.2.17 on 2026-08-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="network.device",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="billing.tariff",
            ),
        ),
    ]
