# Generated by Django 5.2.17 on 2026-08-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("quote", "Quote"),
                    ("proforma", "Pro Forma Invoice"),
                    ("draft", "Draft"),
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
