# Generated by Django 5.2.17 on 2026-08-14 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_invoice_status"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("product", "Stock item"),
                    ("tariff", "Tariff plan"),
                ],
                default="custom",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="billing.tariff",
            ),
        ),
    ]
