# Generated by Django 5.2.17 on 2026-08-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_creditrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="radius_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="radius_username",
            field=models.CharField(
                blank=True,
                help_text="Login name the customer's Mikrotik/OVPN client authenticates with. Blank = RADIUS login disabled for this service.",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
    ]
