# Generated by Django 5.2.17 on 2026-08-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_service_radius_password_service_radius_username"),
        ("network", "0004_device_api_wan_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="ip_assignment_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual (static public IP)"),
                    ("pool", "Select from Customer IP Pool"),
                    ("auto", "Automatically assign from Customer IP Pool"),
                ],
                default="auto",
                help_text="How this PPPoE service's public IP is handed out. Ignored for OVPN services.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="ip_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer IP Pool this service's address comes from when ip_assignment_mode is 'pool' or 'auto'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pppoe_services",
                to="network.ippool",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="radius_connection_type",
            field=models.CharField(
                choices=[("ovpn", "OVPN"), ("pppoe", "PPPoE")],
                default="ovpn",
                help_text="Which RADIUS/NAS setup this service's radius_username authenticates against.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="static_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Static public IP sent as Framed-IP-Address when ip_assignment_mode='manual'. Not tracked in any IP Pool.",
                null=True,
            ),
        ),
    ]
