# Generated by Django 5.2.17 on 2026-08-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_service_ip_assignment_mode_service_ip_pool_and_more"),
        ("network", "0006_device_block_disabled_customers_device_enable_mpsk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="connection_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional speed override for this specific service instead of its tariff's plan speed. Must belong to this service's device.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="network.connectionrule",
            ),
        ),
    ]
