# Generated by Django 5.2.17 on 2026-08-17 04:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_invoicedeletionrequest"),
        ("customers", "0005_partner_customer_partner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReminderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "static_days",
                    models.BooleanField(
                        default=True,
                        help_text="Reminders fire this many days before/after due date (a fixed number per reminder). Dynamic day calculation isn't implemented yet.",
                    ),
                ),
                ("reminder_1_enabled", models.BooleanField(default=True)),
                ("reminder_2_enabled", models.BooleanField(default=True)),
                ("reminder_3_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reminder settings",
                "verbose_name_plural": "Reminder settings",
            },
        ),
        migrations.CreateModel(
            name="CustomerBillingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_period",
                    models.CharField(
                        choices=[
                            ("monthly", "1 month"),
                            ("quarterly", "3 months"),
                            ("biannually", "6 months"),
                            ("annually", "12 months"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "billing_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Day of the month recurring invoices are generated (1-28).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "use_date_of_customer_creation",
                    models.BooleanField(
                        default=False,
                        help_text="Bill on the anniversary of the customer's creation date instead of billing_day.",
                    ),
                ),
                (
                    "payment_due_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after the document date payment is due. Blank = due the same day it's issued.",
                        null=True,
                    ),
                ),
                (
                    "blocking_period_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after payment is due before this customer's services are automatically suspended. Blank = never auto-suspend.",
                        null=True,
                    ),
                ),
                (
                    "deactivation_period_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after blocking before further action is taken. Configurable, but not yet wired to any action -- reserved for a future release.",
                        null=True,
                    ),
                ),
                (
                    "minimum_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="How far into credit/negative a customer's balance can go before the blocking period above starts counting.",
                        max_digits=12,
                    ),
                ),
                ("auto_create_invoices", models.BooleanField(default=True)),
                ("send_billing_notifications", models.BooleanField(default=True)),
                (
                    "auto_proforma_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Generate a pro forma invoice instead of a real invoice each cycle.",
                    ),
                ),
                (
                    "proforma_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "proforma_payment_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "1 month"),
                            ("quarterly", "3 months"),
                            ("biannually", "6 months"),
                            ("annually", "12 months"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "create_proforma_for",
                    models.CharField(
                        choices=[
                            ("current_month", "Current month"),
                            ("next_month", "Next month"),
                        ],
                        default="current_month",
                        max_length=20,
                    ),
                ),
                ("reminder_enabled", models.BooleanField(default=False)),
                (
                    "reminder_1_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reminder_2_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reminder_3_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "billing_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether recurring invoicing/reminders/auto-suspension run for this customer at all.",
                    ),
                ),
                ("billing_name", models.CharField(blank=True, max_length=255)),
                ("billing_street", models.CharField(blank=True, max_length=255)),
                ("billing_zip", models.CharField(blank=True, max_length=20)),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_config",
                        to="customers.customer",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="billing.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_period",
                    models.CharField(
                        choices=[
                            ("monthly", "1 month"),
                            ("quarterly", "3 months"),
                            ("biannually", "6 months"),
                            ("annually", "12 months"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "billing_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Day of the month recurring invoices are generated (1-28).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "use_date_of_customer_creation",
                    models.BooleanField(
                        default=False,
                        help_text="Bill on the anniversary of the customer's creation date instead of billing_day.",
                    ),
                ),
                (
                    "payment_due_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after the document date payment is due. Blank = due the same day it's issued.",
                        null=True,
                    ),
                ),
                (
                    "blocking_period_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after payment is due before this customer's services are automatically suspended. Blank = never auto-suspend.",
                        null=True,
                    ),
                ),
                (
                    "deactivation_period_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after blocking before further action is taken. Configurable, but not yet wired to any action -- reserved for a future release.",
                        null=True,
                    ),
                ),
                (
                    "minimum_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="How far into credit/negative a customer's balance can go before the blocking period above starts counting.",
                        max_digits=12,
                    ),
                ),
                ("auto_create_invoices", models.BooleanField(default=True)),
                ("send_billing_notifications", models.BooleanField(default=True)),
                (
                    "auto_proforma_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Generate a pro forma invoice instead of a real invoice each cycle.",
                    ),
                ),
                (
                    "proforma_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "proforma_payment_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "1 month"),
                            ("quarterly", "3 months"),
                            ("biannually", "6 months"),
                            ("annually", "12 months"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "create_proforma_for",
                    models.CharField(
                        choices=[
                            ("current_month", "Current month"),
                            ("next_month", "Next month"),
                        ],
                        default="current_month",
                        max_length=20,
                    ),
                ),
                ("reminder_enabled", models.BooleanField(default=False)),
                (
                    "reminder_1_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reminder_2_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reminder_3_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="billing.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing defaults",
                "verbose_name_plural": "Billing defaults",
            },
        ),
        migrations.CreateModel(
            name="RecurringBillingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_date",
                    models.DateField(help_text="The billing date this run was for."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("processed", "Processed"), ("failed", "Failed")],
                        default="processed",
                        max_length=10,
                    ),
                ),
                ("status_message", models.CharField(blank=True, max_length=255)),
                ("invoices_created_count", models.PositiveIntegerField(default=0)),
                (
                    "proforma_invoices_created_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("reminders_sent_count", models.PositiveIntegerField(default=0)),
                ("suspensions_applied_count", models.PositiveIntegerField(default=0)),
                (
                    "partners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which partners' customers this run was scoped to. Empty = every partner.",
                        related_name="recurring_billing_runs",
                        to="customers.partner",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member who clicked Run. Every run is staff-triggered this release -- see the design doc's phased rollout.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_created",
                to="billing.recurringbillingrun",
            ),
        ),
    ]
