# Generated by Django 5.2.17 on 2026-08-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_paymentmethod_remindersettings_customerbillingconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspensionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_suspend_enabled",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Master switch for auto-suspension. When off, the recurring-billing "
                            "engine never suspends anyone, regardless of any customer's own "
                            "blocking_period_days. When on, suspension still only applies to "
                            "customers who are billing_enabled AND have a blocking_period_days set."
                        ),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Suspension settings",
                "verbose_name_plural": "Suspension settings",
            },
        ),
    ]
