# Generated by Django 5.2.17 on 2026-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_suspensionsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdefaults",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="Skybre's own SARS VAT registration number.",
                max_length=32,
            ),
        ),
    ]
