# Generated by Django 5.2.17 on 2026-08-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_billingdefaults_vat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdefaults",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="bank_branch_code",
            field=models.CharField(blank=True, help_text="e.g. 250655.", max_length=20),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="bank_name",
            field=models.CharField(blank=True, help_text="e.g. FNB.", max_length=100),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="company_address",
            field=models.CharField(
                blank=True,
                help_text="Street address line, e.g. Cnr Reitz & Botha Street.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="company_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="company_country",
            field=models.CharField(blank=True, default="South Africa", max_length=100),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="company_email",
            field=models.EmailField(
                blank=True,
                help_text="Billing address shown on invoices, e.g. accounts@skybre.co.za.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="company_legal_name",
            field=models.CharField(
                blank=True,
                help_text='Registered name as it must appear on a tax invoice, e.g. "Skybre Pty Ltd".',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="company_phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="company_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="billingdefaults",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Printed top-left on invoices and statements. A PNG with a transparent background works best.",
                null=True,
                upload_to="branding/",
            ),
        ),
    ]
