# Generated by Django 5.2.17 on 2026-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_billingdefaults_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="auto_suspended_with_customer",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
