# Generated by Django 5.2.17 on 2026-08-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_tariff_speeds_in_kbps"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="pending_tariff",
            field=models.ForeignKey(
                blank=True,
                help_text="Tariff to switch this service to on the effective date below.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_services",
                to="billing.tariff",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="pending_tariff_date",
            field=models.DateField(
                blank=True,
                help_text="The date the new tariff starts applying. Set it to the first day of a billing period — a mid-period change is not prorated, so the whole period bills at the new price.",
                null=True,
                verbose_name="Change takes effect",
            ),
        ),
    ]
