# Generated by Django 5.2.17 on 2026-08-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_service_pending_tariff_service_pending_tariff_date"),
        ("network", "0008_networksite_partners"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="access_detail",
            field=models.CharField(
                blank=True,
                help_text='Port, sector or SSID on that device — e.g. "Sector B 120°", "PON 1/3", "ether7".',
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="access_device",
            field=models.ForeignKey(
                blank=True,
                help_text="The AP, sector, OLT or switch this client actually connects to. Not the NAS — see `device`.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_services",
                to="network.device",
            ),
        ),
    ]
