# Generated by Django 5.2.17 on 2026-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_service_access_detail_service_access_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="fup_exempt",
            field=models.BooleanField(
                default=False,
                help_text="Never shape this line, whatever the tariff says. For business lines and staff.",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="fup_speed_pct",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Overrides the tariff's shaped speed for this line only. Blank = use the tariff's.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="fup_threshold_gb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Overrides the tariff's fair-use threshold for this line only. Blank = use the tariff's.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="last_pushed_rate_limit",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="tariff",
            name="fup_speed_pct",
            field=models.PositiveIntegerField(
                default=30,
                help_text="What the line runs at once past the threshold. 30 = 30% of plan speed.",
                verbose_name="Shaped speed (% of plan)",
            ),
        ),
        migrations.AddField(
            model_name="tariff",
            name="fup_threshold_gb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Blank = no fair-use shaping. Usage past this in a calendar month shapes the line.",
                null=True,
                verbose_name="Fair-use threshold (GB)",
            ),
        ),
    ]
