# Generated by Django 5.2.17 on 2026-09-03 07:28
"""Adds the never-reuse mark for document numbers, and the flag recording
whether an invoice's total is currently included in Customer.balance.

`balance_debited` is deliberately left False on every existing row --
including recurring-billing invoices that really were debited. See the
field's comment in models.py: False is the only value that cannot
introduce a NEW error, because it means "reversing this invoice credits
nothing", which is exactly what those rows do today. The historical drift
is reported by `manage.py balance_drift`, and repaired deliberately, not
guessed at here.

The high-water marks ARE seeded, because that value is read off the
existing numbers rather than guessed: it is simply the highest number
each prefix has actually issued. Without it, deleting the newest invoice
before any new one is created would still hand its number away.
"""
from django.db import migrations, models


def seed_high_water_marks(apps, schema_editor):
    import re

    Invoice = apps.get_model("billing", "Invoice")
    HighWater = apps.get_model("billing", "IssuedNumberHighWater")

    highest = {}
    for number in Invoice.objects.values_list("number", flat=True).iterator():
        match = re.fullmatch(r"([A-Z]{1,10})-(\d{1,9})", number or "")
        if not match:
            # Legacy or hand-edited references are skipped, the same way
            # Invoice._next_number_for_status skips them.
            continue
        prefix, seq = match.group(1), int(match.group(2))
        if seq > highest.get(prefix, 0):
            highest[prefix] = seq

    HighWater.objects.bulk_create(
        [HighWater(prefix=prefix, last_seq=seq) for prefix, seq in highest.items()]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_service_fup_exempt_service_fup_speed_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedNumberHighWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('last_seq', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'issued number high-water mark',
                'verbose_name_plural': 'issued number high-water marks',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_debited',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(seed_high_water_marks, migrations.RunPython.noop),
    ]
