# Generated by Django 5.2.17 on 2026-09-03 13:11
"""Make `balance_debited` nullable, and set every pre-existing invoice to
NULL so the ledger leaves it completely alone.

0019 defaulted every existing row to False, on the reasoning that False
was the value that could not introduce a new error because "reversing
this invoice credits nothing". That reasoning only covered the RELEASE
direction. False is not neutral -- it means "not yet debited" -- and
Invoice.apply_balance_debit() runs on every invoice update, not only on
a status change. So the first PATCH of any legacy UNPAID invoice, such as
marking it overdue from the Finance list, re-added a total that the old
recurring code had ALREADY put into Customer.balance, silently doubling
the customer's debt. Only ever upward, because the release side was
correctly inert.

NULL is genuinely inert: both apply_balance_debit and
release_balance_debit return immediately on it. Legacy invoices keep
exactly the balance contribution they have today, right or wrong, and
`manage.py balance_drift` is what measures that.

Every row is set to NULL rather than only the ones 0019 touched. On the
live server the two migrations run together (deploys never `git pull`;
0019 has not been applied there), so "every row" and "every row 0019
touched" are the same set. On a database where 0019 already ran, an
invoice created in between could legitimately be False or True: True is
preserved, and a False one becomes inert, which loses a future release
rather than inventing money. That is the safe direction.
"""
from django.db import migrations, models


def make_existing_invoices_inert(apps, schema_editor):
    Invoice = apps.get_model("billing", "Invoice")
    Invoice.objects.filter(balance_debited=False).update(balance_debited=None)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_issuednumberhighwater_invoice_balance_debited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance_debited',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.RunPython(make_existing_invoices_inert, migrations.RunPython.noop),
    ]
