# Generated by Django 5.2.17 on 2026-08-14 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_vehicle_fuel_type_fuellog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__in": [
                        "admin",
                        "support",
                        "sales",
                        "technician",
                        "management",
                        "accounts",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
