# Generated by Django 5.2.17 on 2026-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_alter_vehicle_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="in_service_since",
            field=models.DateField(
                blank=True,
                help_text="Date it went in for a service. Set = at the workshop now. Cleared automatically when a service is logged.",
                null=True,
            ),
        ),
    ]
