# Generated by Django 5.2.17 on 2026-08-13 23:34

from django.db import migrations, models


def blocked_to_suspended(apps, schema_editor):
    """The 'blocked' status was renamed to 'suspended' to match the wording
    already used for Service status — migrate any existing rows so no
    customer silently loses/changes its actual status value."""
    Customer = apps.get_model("customers", "Customer")
    Customer.objects.filter(status="blocked").update(status="suspended")


def suspended_to_blocked(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    Customer.objects.filter(status="suspended").update(status="blocked")


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("inactive", "Inactive"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.RunPython(blocked_to_suspended, suspended_to_blocked),
    ]
