# Generated by Django 5.2.17 on 2026-08-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customerdeletionrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "commission_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional commission percentage owed to this partner, e.g. 10.00 for 10%.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Reseller partner this customer belongs to, if any. Blank = a direct (non-partner) customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="customers.partner",
            ),
        ),
    ]
