# Generated by Django 5.2.17 on 2026-08-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_partner_customer_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="signup_date",
            field=models.DateField(
                blank=True,
                help_text="Original signup date, for customers migrated from another platform. Leave blank for customers created here — their created date is used instead.",
                null=True,
            ),
        ),
    ]
