# Generated by Django 5.2.17 on 2026-08-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_customer_usage_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(
                blank=True,
                help_text="What this customer types as the reference on their EFT/bank transfer. Leave blank to generate the next CUS-###### automatically.",
                max_length=20,
                unique=True,
                verbose_name="Payment reference",
            ),
        ),
    ]
