# Generated by Django 5.2.17 on 2026-08-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_alter_customer_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="ID number, or company registration number for a business.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="The customer's own VAT registration number, if they have one.",
                max_length=32,
            ),
        ),
    ]
