# Generated by Django 5.2.17 on 2026-08-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_customer_id_number_customer_vat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="live_bandwidth_public",
            field=models.BooleanField(
                default=False,
                help_text="Off by default. When on, this customer can watch their own live speed graph.",
                verbose_name="Show live bandwidth on their usage link",
            ),
        ),
    ]
