# Generated by Django 5.2.17 on 2026-08-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_customer_live_bandwidth_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="live_bandwidth_public",
            field=models.BooleanField(
                default=False,
                help_text="Off by default. When on, this customer sees a live speed figure in the portal and on their usage link, which holds a connection to their router open while they watch.",
                verbose_name="Let this customer see their live speed",
            ),
        ),
    ]
