# Generated by Django 5.2.17 on 2026-08-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_alter_customer_live_bandwidth_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="live_bandwidth_last_viewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the customer actually loaded a live view. Set when staff enable it, so the idle clock starts even if they never look.",
                null=True,
            ),
        ),
    ]
