# Generated by Django 5.2.17 on 2026-08-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_customer_live_bandwidth_last_viewed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("bad_debt", "Bad Debt"),
                    ("inactive", "Inactive"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
