# Generated by Django 5.2.17 on 2026-08-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("router", "Router"),
                            ("switch", "Switch"),
                            ("olt", "OLT"),
                            ("access_point", "Access Point"),
                            ("server", "Server"),
                            ("onu", "ONU/CPE"),
                        ],
                        default="router",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "snmp_community",
                    models.CharField(
                        blank=True,
                        default="public",
                        help_text="SNMP read community string. Wire real polling to network.monitoring against this field.",
                        max_length=100,
                    ),
                ),
                ("snmp_version", models.CharField(default="2c", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IPPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "network_cidr",
                    models.CharField(help_text="e.g. 10.10.0.0/24", max_length=64),
                ),
                ("gateway", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "pool_type",
                    models.CharField(
                        choices=[("ipv4", "IPv4"), ("ipv6", "IPv6")],
                        default="ipv4",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("assigned", "Assigned"),
                            ("reserved", "Reserved"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_addresses",
                        to="billing.service",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="network.ippool",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "IP addresses",
                "ordering": ["address"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("is_up", models.BooleanField(default=True)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("packet_loss_pct", models.FloatField(blank=True, null=True)),
                ("bandwidth_in_mbps", models.FloatField(blank=True, null=True)),
                ("bandwidth_out_mbps", models.FloatField(blank=True, null=True)),
                ("cpu_pct", models.FloatField(blank=True, null=True)),
                ("memory_pct", models.FloatField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="network.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="network_mon_device__5b532b_idx",
                    )
                ],
            },
        ),
    ]
