# Generated by Django 5.2.17 on 2026-08-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ippool",
            name="category",
            field=models.CharField(
                choices=[("customer", "Customer IP Pool"), ("network", "Net IP Pool")],
                default="customer",
                max_length=10,
            ),
        ),
    ]
