# Generated by Django 5.2.17 on 2026-08-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_ippool_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="api_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Talk to this device's real RouterOS API (monitoring, live sessions, config push) instead of only simulated readings.",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="api_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="api_port",
            field=models.PositiveIntegerField(
                default=8728,
                help_text="RouterOS API port -- 8728 plaintext, 8729 with SSL.",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="api_use_ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="api_username",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
