# Generated by Django 5.2.17 on 2026-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_device_api_enabled_device_api_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="api_wan_interface",
            field=models.CharField(
                blank=True,
                help_text="Interface name to read bandwidth from, e.g. ether1 or ovpn-server1. Leave blank to skip bandwidth polling.",
                max_length=64,
            ),
        ),
    ]
