# Generated by Django 5.2.17 on 2026-08-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_partner_customer_partner"),
        ("network", "0004_device_api_wan_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="visible_partners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Partners whose staff can see this device. Empty = visible to everyone with Networking access.",
                related_name="visible_devices",
                to="customers.partner",
            ),
        ),
        migrations.AddField(
            model_name="ippool",
            name="network_type",
            field=models.CharField(
                choices=[("endnet", "EndNet"), ("rootnet", "RootNet")],
                default="endnet",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ippool",
            name="root_net",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent network this pool is carved out of, for grouping/reporting only.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_nets",
                to="network.ippool",
            ),
        ),
        migrations.CreateModel(
            name="ConnectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("speed_down_kbps", models.PositiveIntegerField(default=0)),
                ("speed_up_kbps", models.PositiveIntegerField(default=0)),
                (
                    "guaranteed_pct",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Guaranteed speed floor, as a percentage of the speeds above.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_rules",
                        to="network.device",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="NetworkSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Free-text region/area, for filtering the site list.",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="network_sites",
                        to="customers.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical site/tower this device is mounted at, if tracked (see Networking -> Sites).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="network.networksite",
            ),
        ),
    ]
