# Generated by Django 5.2.17 on 2026-08-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_device_visible_partners_ippool_network_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="block_disabled_customers",
            field=models.BooleanField(
                default=False,
                help_text="When on, suspended/terminated/pending customers' Services on this device are automatically pushed into a router-side address-list + firewall drop rule, cutting off their traffic. Toggle off (then Sync) to remove that address-list/rule from the router.",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="enable_mpsk",
            field=models.BooleanField(
                default=False,
                help_text="Allow setting a per-client WPA2 passphrase (MPSK) on wireless Access List entries for this device.",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="enable_shaper",
            field=models.BooleanField(
                default=False,
                help_text="When on, every active Service on this device gets a real RouterOS Simple Queue bandwidth limit pushed to the router (its tariff speed, or a Connection Rule override if one is assigned). Toggle off (then Sync) to remove those queues from the router.",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="enable_wireless_access_list",
            field=models.BooleanField(
                default=False,
                help_text="Allow managing this device's RouterOS wireless Access List from the Networking page.",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="shaping_type",
            field=models.CharField(
                default="simple_queue",
                help_text="Which RouterOS mechanism the shaper uses. Only 'simple_queue' is implemented for now.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="wireless_interface",
            field=models.CharField(
                blank=True,
                help_text="Wireless interface name (e.g. wlan1) the Access List/MPSK actions apply to.",
                max_length=64,
            ),
        ),
    ]
