# Generated by Django 5.2.17 on 2026-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_device_block_disabled_customers_device_enable_mpsk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ippool",
            name="category",
            field=models.CharField(
                choices=[
                    ("customer", "Customer IP Pool"),
                    ("network", "Net IP Pool"),
                    ("walled_garden", "Walled Garden (no internet)"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
