# Generated by Django 5.2.17 on 2026-08-22 20:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_stockreceipt_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockreceipt",
            name="prices_include_vat",
            field=models.BooleanField(
                default=False,
                help_text="Tick if the unit costs below were typed exactly as they appear on a VAT-inclusive supplier invoice. Leave unticked for VAT-exclusive prices.",
            ),
        ),
        migrations.AddField(
            model_name="stockreceiptline",
            name="vat_rate_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="VAT rate for this line. Pre-filled from the supplier; override it for zero-rated or imported items. Blank means VAT was never recorded — the line is then left out of the VAT return rather than guessed at.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="default_vat_rate_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15"),
                help_text="Pre-fills the VAT rate on each new receipt line for this supplier. Ignored while 'VAT registered' is unchecked.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_vat_registered",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck for a supplier not registered for VAT — their receipt lines default to 0% and no Input VAT can be claimed on them.",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="The supplier's own SARS VAT registration number, as printed on their invoices.",
                max_length=32,
            ),
        ),
    ]
