# Generated by Django 5.2.17 on 2026-08-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_stockreceipt_prices_include_vat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="default_prices_include_vat",
            field=models.BooleanField(
                default=False,
                help_text="How this supplier normally quotes prices. Pre-fills the 'unit costs include VAT' toggle when checking in their stock.",
            ),
        ),
    ]
