# Generated by Django 5.2.17 on 2026-08-24 08:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_supplier_default_prices_include_vat"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sell_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="What a customer is charged for one of these, excluding VAT. Blank = not for resale.",
                max_digits=10,
                null=True,
                verbose_name="Resell price (excl. VAT)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sell_tax_rate_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15"),
                help_text="VAT charged when selling this item. 0 for a zero-rated item.",
                max_digits=5,
                verbose_name="Resell VAT rate (%)",
            ),
        ),
    ]
