# Generated by Django 5.2.17 on 2026-08-27 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0016_service_pending_tariff_service_pending_tariff_date"),
        ("customers", "0013_alter_customer_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("phone", "Phone enquiry"),
                            ("referral", "Referral"),
                            ("website", "Website"),
                            ("social", "Social media"),
                            ("reseller", "Reseller"),
                            ("campaign", "Campaign"),
                            ("existing_customer", "Existing customer"),
                            ("other", "Other"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                ("source_detail", models.CharField(blank=True, max_length=255)),
                (
                    "estimated_monthly_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "lost_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_coverage", "No coverage"),
                            ("price", "Price"),
                            ("competitor", "Went with a competitor"),
                            ("went_quiet", "Went quiet"),
                            ("not_ready", "Not ready yet"),
                            ("duplicate", "Duplicate enquiry"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "next_follow_up",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="When to chase them next. Blank means nothing is scheduled.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "role__in": ["admin", "support", "sales", "management"]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originating_leads",
                        to="customers.customer",
                    ),
                ),
                (
                    "interested_tariff",
                    models.ForeignKey(
                        blank=True,
                        help_text="What they asked about. Sets the pipeline value unless overridden below.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="billing.tariff",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reseller this enquiry came through, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="customers.partner",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_label", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("system", "System"),
                        ],
                        default="note",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_notes",
                        to="sales.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "next_follow_up"], name="sales_lead_status_78ffc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to", "status"], name="sales_lead_assigne_c6b285_idx"
            ),
        ),
    ]
