# Generated by Django 5.2.17 on 2026-08-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RadCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("attribute", models.CharField(max_length=255)),
                ("op", models.CharField(default="==", max_length=2)),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "radcheck",
            },
        ),
        migrations.CreateModel(
            name="RadiusNasClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name, e.g. 'Teraco JHB Mikrotik'.",
                        max_length=150,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="The Mikrotik's IP address as seen by the FreeRADIUS server."
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="Short identifier used in FreeRADIUS logs, e.g. 'mikrotik-jhb'.",
                        max_length=64,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Shared RADIUS secret configured identically on the Mikrotik.",
                        max_length=128,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RadReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("attribute", models.CharField(max_length=255)),
                ("op", models.CharField(default="=", max_length=2)),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "radreply",
            },
        ),
        migrations.CreateModel(
            name="RadAcct",
            fields=[
                ("radacctid", models.BigAutoField(primary_key=True, serialize=False)),
                ("acctsessionid", models.CharField(max_length=64)),
                ("acctuniqueid", models.CharField(max_length=32, unique=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("groupname", models.CharField(blank=True, max_length=255, null=True)),
                ("realm", models.CharField(blank=True, max_length=64, null=True)),
                ("nasipaddress", models.GenericIPAddressField()),
                ("nasportid", models.CharField(blank=True, max_length=32, null=True)),
                ("nasporttype", models.CharField(blank=True, max_length=32, null=True)),
                ("acctstarttime", models.DateTimeField(blank=True, null=True)),
                ("acctupdatetime", models.DateTimeField(blank=True, null=True)),
                ("acctstoptime", models.DateTimeField(blank=True, null=True)),
                ("acctinterval", models.BigIntegerField(blank=True, null=True)),
                ("acctsessiontime", models.BigIntegerField(blank=True, null=True)),
                (
                    "acctauthentic",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "connectinfo_start",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "connectinfo_stop",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("acctinputoctets", models.BigIntegerField(blank=True, null=True)),
                ("acctoutputoctets", models.BigIntegerField(blank=True, null=True)),
                (
                    "calledstationid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "callingstationid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "acctterminatecause",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("servicetype", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "framedprotocol",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "framedipaddress",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "framedipv6address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "framedipv6prefix",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "framedinterfaceid",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "delegatedipv6prefix",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "db_table": "radacct",
                "ordering": ["-acctstarttime"],
                "indexes": [
                    models.Index(
                        fields=["username", "-acctstarttime"],
                        name="radacct_usernam_ca84a6_idx",
                    )
                ],
            },
        ),
    ]
