# Generated by Django 5.2.17 on 2026-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiusauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvpnSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "freeradius_ip",
                    models.CharField(
                        blank=True,
                        help_text="Default FreeRADIUS server IP/hostname, pre-filled into the 'Push to router' action under Networking -> RADIUS Clients.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Free-text notes for staff -- e.g. links to RADIUS_SETUP.md, reminders about clients.conf.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
