# Generated by Django 5.2.17 on 2026-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiusauth", "0002_ovpnsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiusnasclient",
            name="realm",
            field=models.CharField(
                blank=True,
                help_text="Optional site/region tag (e.g. 'jhb') for reporting/segmentation only -- does not change live routing.",
                max_length=64,
            ),
        ),
    ]
