# Generated by Django 5.2.17 on 2026-08-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiusauth", "0003_radiusnasclient_realm"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvpnClientConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Connection name, e.g. 'skybre' -- becomes the systemd unit name (openvpn-client@<name>) once installed.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "remote_ip",
                    models.CharField(
                        help_text="Remote OpenVPN server address (IP or hostname).",
                        max_length=255,
                    ),
                ),
                ("remote_port", models.PositiveIntegerField(default=1194)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("password", models.CharField(blank=True, max_length=255)),
                (
                    "routes",
                    models.TextField(
                        blank=True,
                        help_text="One route per line: <network> <netmask> <gateway>, e.g. '10.0.0.0 255.0.0.0 10.250.32.2'.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Staff-facing intent only -- toggling this does not itself start/stop anything on the VPS; it's a reminder of whether this tunnel is supposed to be active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
