# Generated by Django 5.2.17 on 2026-08-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_service_pending_tariff_service_pending_tariff_date"),
        ("radiusauth", "0007_drop_duplicate_username_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiusAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("coa_rate", "Change speed on live session"),
                            ("disconnect", "Disconnect live session"),
                            ("none", "Nothing to do"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("coa", "RADIUS CoA (RFC 5176)"),
                            ("api", "RouterOS API"),
                            ("none", "Not attempted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ok", models.BooleanField()),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="radius_actions",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
