# Generated by Django 5.2.17 on 2026-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiusauth", "0008_radiusaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("bucket_start", models.DateTimeField(db_index=True)),
                ("download_bytes", models.BigIntegerField(default=0)),
                ("upload_bytes", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["bucket_start"],
                "indexes": [
                    models.Index(
                        fields=["username", "bucket_start"],
                        name="usage_bucket_user_time",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("username", "bucket_start"),
                        name="usage_bucket_unique_hour",
                    )
                ],
            },
        ),
    ]
