# Generated by Django 5.2.17 on 2026-08-27 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_alter_ippool_category"),
        ("radiusauth", "0009_usagebucket"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveTrafficInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_requested_at", models.DateTimeField(db_index=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_interest",
                        to="network.device",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "live traffic interest",
            },
        ),
    ]
