# Generated by Django 5.2.17 on 2026-08-27 14:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0018_service_fup_exempt_service_fup_speed_pct_and_more"),
        ("radiusauth", "0010_livetrafficinterest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeedWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Night burst", "Sunday afternoon".',
                        max_length=100,
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "end_time",
                    models.TimeField(
                        help_text="May be earlier than the start, for a window that runs through midnight."
                    ),
                ),
                (
                    "weekdays",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        blank=True,
                        default=list,
                        help_text="Days it applies to (0=Mon … 6=Sun). Empty = every day.",
                        size=None,
                    ),
                ),
                (
                    "speed_pct",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Percent of the plan speed while this window is on. 200 = double, 100 = no change.",
                    ),
                ),
                (
                    "counts_toward_fup",
                    models.BooleanField(
                        default=False,
                        help_text="Off (recommended): traffic in this window doesn't count toward fair use.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tariff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to apply to every tariff.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speed_windows",
                        to="billing.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time", "name"],
            },
        ),
    ]
