# Generated by Django 5.2.17 on 2026-08-19 22:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_alter_stockissue_issued_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        help_text="Supplier/payee name, if not linked to a Supplier record above.",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bandwidth", "Bandwidth / Transit"),
                            ("equipment", "Equipment / Hardware"),
                            ("fuel", "Fuel / Vehicles"),
                            ("rent", "Rent / Facilities"),
                            ("utilities", "Utilities"),
                            ("software", "Software / Subscriptions"),
                            ("professional", "Professional fees (legal / accounting)"),
                            ("salaries", "Salaries / Payroll"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="The supplier's own invoice/receipt number, if any.",
                        max_length=100,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The date on the supplier's invoice/receipt -- this determines which VAT period this expense's Input VAT falls into."
                    ),
                ),
                (
                    "amount_excl_vat",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "vat_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15"),
                        help_text="0 for zero-rated/exempt purchases (e.g. most bank charges) -- no Input VAT can be claimed on those.",
                        max_digits=5,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="expense_receipts/%Y/%m/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to an existing Supplier record (Stock / Inventory -> Suppliers).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
