# Generated by Django 5.2.17 on 2026-08-19 23:19

import config.uploads
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount_excl_vat",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="expense_receipts/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "png",
                            "jpg",
                            "jpeg",
                            "webp",
                            "heic",
                            "gif",
                            "txt",
                        ]
                    ),
                    config.uploads.validate_attachment_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="vat_rate_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15"),
                help_text="0 for zero-rated/exempt purchases (e.g. most bank charges) -- no Input VAT can be claimed on those.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
