# Generated by Django 5.2.17 on 2026-08-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="id_number",
            field=models.CharField(
                blank=True, help_text="National ID / passport number.", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="license_number",
            field=models.CharField(
                blank=True, help_text="Driver's license number.", max_length=30
            ),
        ),
    ]
