# Generated by Django 5.2.17 on 2026-08-14 22:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_staffprofile_id_number_staffprofile_license_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="annual_leave_balance",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("21.0"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="family_responsibility_leave_balance",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("3.0"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="sick_leave_balance",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("30.0"), max_digits=5
            ),
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual leave"),
                            ("sick", "Sick leave"),
                            ("family_responsibility", "Family responsibility leave"),
                        ],
                        max_length=25,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_attachments/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decision_note", models.CharField(blank=True, max_length=255)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["admin", "staff", "technician"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
    ]
