# Generated by Django 5.2.17 on 2026-08-14 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_staffprofile_annual_leave_balance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="staff",
            field=models.ForeignKey(
                limit_choices_to={
                    "role__in": [
                        "admin",
                        "support",
                        "sales",
                        "technician",
                        "management",
                        "accounts",
                    ]
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="staff",
            field=models.ForeignKey(
                limit_choices_to={
                    "role__in": [
                        "admin",
                        "support",
                        "sales",
                        "technician",
                        "management",
                        "accounts",
                    ]
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={
                    "role__in": [
                        "admin",
                        "support",
                        "sales",
                        "technician",
                        "management",
                        "accounts",
                    ]
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
