# Generated by Django 5.2.17 on 2026-08-19 23:19

import config.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_alter_attendancerecord_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="leave_attachments/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "png",
                            "jpg",
                            "jpeg",
                            "webp",
                            "heic",
                            "gif",
                            "txt",
                        ]
                    ),
                    config.uploads.validate_attachment_size,
                ],
            ),
        ),
    ]
