# Generated by Django 5.2.17 on 2026-08-24 10:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_alter_leaverequest_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uif_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Employee UIF contribution, % of remuneration. Employer contributes the same again.",
                        max_digits=5,
                    ),
                ),
                (
                    "uif_monthly_ceiling",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("17712.00"),
                        help_text="UIF is only charged on remuneration up to this amount per month. Check the current figure.",
                        max_digits=10,
                    ),
                ),
                (
                    "sdl_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Skills Development Levy, % of payroll. Employer cost only.",
                        max_digits=5,
                    ),
                ),
                (
                    "sdl_applicable",
                    models.BooleanField(
                        default=False,
                        help_text="SDL only applies once your annual payroll exceeds the registration threshold. Off by default.",
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                ("employer_address", models.CharField(blank=True, max_length=255)),
                (
                    "paye_reference",
                    models.CharField(
                        blank=True,
                        help_text="Your SARS PAYE reference number.",
                        max_length=30,
                    ),
                ),
                (
                    "uif_reference",
                    models.CharField(
                        blank=True,
                        help_text="Your UIF reference number.",
                        max_length=30,
                    ),
                ),
                (
                    "payslip_note",
                    models.CharField(
                        blank=True,
                        help_text="Optional line printed at the bottom of every payslip, e.g. who to contact about a query.",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payroll settings",
                "verbose_name_plural": "Payroll settings",
            },
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="additional_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bonus, commission, allowance — anything paid on top of the hours worked.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="additional_description",
            field=models.CharField(
                blank=True,
                help_text='What the extra amount is for, e.g. "December bonus".',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="notes",
            field=models.CharField(
                blank=True, help_text="Printed on the payslip.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="other_deduction_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Loan repayment, garnishee, staff purchase — anything else withheld.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="other_deduction_description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="paye",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Income tax withheld, from your accountant or SARS eFiling. Not calculated here — see the model docstring.",
                max_digits=10,
                verbose_name="PAYE",
            ),
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="sdl",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Skills Development Levy — employer cost, not an employee deduction.",
                max_digits=10,
                verbose_name="SDL",
            ),
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="uif_employee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="UIF (employee)",
            ),
        ),
        migrations.AddField(
            model_name="payrollrunline",
            name="uif_employer",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="UIF (employer)",
            ),
        ),
    ]
