# Generated by Django 5.2.17 on 2026-08-17 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "billing",
            "0010_paymentmethod_remindersettings_customerbillingconfig_and_more",
        ),
        ("customers", "0005_partner_customer_partner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "FNB Cheque - Head Office"', max_length=100
                    ),
                ),
                ("account_number", models.CharField(blank=True, max_length=30)),
                (
                    "branch_code",
                    models.CharField(
                        blank=True, help_text="e.g. 250655 for FNB.", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "api_base_url",
                    models.CharField(
                        blank=True,
                        help_text="Base URL for FNB's transaction API once access is confirmed. Leave blank if only using CSV import.",
                        max_length=255,
                    ),
                ),
                ("api_client_id", models.CharField(blank=True, max_length=255)),
                ("api_client_secret", models.CharField(blank=True, max_length=255)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("last_sync_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankFeedSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("transactions_fetched", models.PositiveIntegerField(default=0)),
                ("transactions_new", models.PositiveIntegerField(default=0)),
                ("transactions_matched", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="bankfeeds.bankaccount",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("api", "Bank API"), ("csv_import", "CSV import")],
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive = money in, negative = money out.",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("matched", "Matched (awaiting confirmation)"),
                            ("confirmed", "Confirmed"),
                            ("ignored", "Ignored"),
                        ],
                        default="unmatched",
                        max_length=10,
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reference", "Reference number"),
                            ("manual", "Manually assigned"),
                        ],
                        max_length=10,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bankfeeds.bankaccount",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transaction",
                        to="billing.payment",
                    ),
                ),
                (
                    "matched_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_transactions",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "unique_together": {("account", "external_id")},
            },
        ),
    ]
