# Generated by Django 5.2.17 on 2026-08-19 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankfeeds", "0001_initial"),
        ("expenses", "0001_initial"),
        ("inventory", "0002_alter_stockissue_issued_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="created_expense",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction",
                to="expenses.expense",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="matched_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transactions",
                to="inventory.supplier",
            ),
        ),
    ]
