# Generated by Django 5.2.17 on 2026-09-03 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('customers', '0014_customertask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_label', 'action', '-created_at'], name='audit_login_guard_idx'),
        ),
    ]
